/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APP_NAME "swayimg"

#define APP_VERSION "3.4-5-g23fc19e"

#define HAVE_INOTIFY

#undef HAVE_LIBAVIF

#define HAVE_LIBEXIF

#undef HAVE_LIBEXR

#undef HAVE_LIBGIF

#undef HAVE_LIBHEIF

#define HAVE_LIBJPEG

#undef HAVE_LIBJXL

#define HAVE_LIBPNG

#undef HAVE_LIBRSVG

#define HAVE_LIBTIFF

#define HAVE_LIBWEBP

